# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artistas',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descrip', models.CharField(max_length=200)),
            ],
        ),
    ]
