# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='canciones',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('id_artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artistas.artistas')),
            ],
        ),
    ]
